server:
  port: 8888
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.109.192:3306/catering?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Wang@2018
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    initalSize: 5
    maxActive: 10
    maxWait: 60000
mybatis-plus:
  type-aliases-package: com.happing.one.domain
  mapper-locations: classpath:/mapper/*.xml
mapper:
  identity: MYSQL # 配置主键自动增长(使用MYSQL原生方式)
# 分页插件
pagehelper:
  reasonable: true
  page-size-zero: true
  params: pageNum=start;pageSize=limit
  support-methods-arguments: true
weixin:
  world:
    appid: wx9a5dff93dfe22055
    secret: 8d6b12a0b125f5c15513787f412fcf78
    url: https://api.weixin.qq.com/sns/jscode2session


